name: CI/CD Pipeline for Node.js lambda
on: 
  pull_request:
    paths:
    - 'lambda/**'
    branches:
        - main
  push:
    paths:
    - 'lambda/**'
    branches:
        - main
jobs:
  continuous-integration:
    name: Test
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        working-directory: ./lambda
        run: npm install
      - name: Test
        working-directory: ./lambda
        run: npm run test
      - name: Create Zipfile archive of Dependencies
        run: cd ./lambda && zip -g ./lambda.zip -r .
      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: lambda
          path: lambda.zip
  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    steps:
      # Step 1
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      # Step 2
      - name: Download Lambda lambda.zip
        uses: actions/download-artifact@v2
        with:
          name: lambda
      # Step 3 - would need to update
      - name: Upload to S3
        run: aws s3 cp lambda.zip s3://ci-cd-demo-bucket/lambda.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      # Step 4 - would need to update
      - name: Deploy new Lambda
        run: aws lambda update-function-code --function-name ci-cd-demo-lambda --s3-bucket ci-cd-demo-bucket --s3-key lambda.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}